/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tablero.Tablero;

/**
 *
 * @author User
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private String usuario = "";
    private String punt = "0";
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String usuario, String punt) {
        initComponents();
        
        // Deshabilitar la redimensión, minimizar y cerrar
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        // Añadir un listener para evitar el cierre de la ventana
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // No hacer nada para evitar el cierre de la ventana
            }
        });
        this.usuario = usuario;
        this.punt = punt;
        
        this.labelUsuario.setText(this.usuario);
        this.labelPunt.setText("Puntuacion: " + this.punt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        labelPunt = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnIA = new javax.swing.JButton();
        btnIJugador = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnAjustes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        labelUsuario.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/userLabel.png"))); // NOI18N
        labelUsuario.setText("Usuario");

        labelPunt.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        labelPunt.setForeground(new java.awt.Color(255, 255, 255));
        labelPunt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/key.png"))); // NOI18N
        labelPunt.setText("Puntuacion: ");

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Cerrar Sesión");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIA.setBackground(new java.awt.Color(60, 78, 234));
        btnIA.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        btnIA.setForeground(new java.awt.Color(255, 255, 255));
        btnIA.setText("Jugador vs IA");
        btnIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIAActionPerformed(evt);
            }
        });

        btnIJugador.setBackground(new java.awt.Color(60, 78, 234));
        btnIJugador.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        btnIJugador.setForeground(new java.awt.Color(255, 255, 255));
        btnIJugador.setText("Jugador vs Jugador");
        btnIJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIJugadorActionPerformed(evt);
            }
        });

        btnTienda.setBackground(new java.awt.Color(60, 78, 234));
        btnTienda.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        btnTienda.setForeground(new java.awt.Color(255, 255, 255));
        btnTienda.setText("Tienda");
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });

        btnAjustes.setBackground(new java.awt.Color(60, 78, 234));
        btnAjustes.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        btnAjustes.setForeground(new java.awt.Color(255, 255, 255));
        btnAjustes.setText("Ajustes");
        btnAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(25, 25, 25))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnIA)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btnIJugador)
                .addGap(38, 168, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAjustes)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPunt)
                .addGap(33, 33, 33)
                .addComponent(btnIJugador)
                .addGap(43, 43, 43)
                .addComponent(btnIA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTienda)
                    .addComponent(btnAjustes))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas salir?", "Confirmar salida",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIAActionPerformed
        Dificultades dif = new Dificultades(this, true);
        dif.setLocationRelativeTo(null);
        dif.setVisible(true);
        
    }//GEN-LAST:event_btnIAActionPerformed

    private void btnIJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIJugadorActionPerformed
        // Creamos JFrame y asignamos sus atributos
        JFrame frame = new JFrame();
        frame.getContentPane().setBackground(Color.black);
        frame.setLayout(new GridBagLayout());
        frame.setMinimumSize(new Dimension(700, 800));
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Añadimos el tablero al frame
        Tablero tablero = new Tablero(0);
        GridBagConstraints gbcTablero = new GridBagConstraints();
        gbcTablero.gridx = 0;
        gbcTablero.gridy = 0;
        gbcTablero.gridwidth = 3; // El tablero ocupa el ancho de tres columnas (donde estarán los botones)
        gbcTablero.fill = GridBagConstraints.BOTH;
        gbcTablero.weightx = 1.0;
        gbcTablero.weighty = 1.0;
        frame.add(tablero, gbcTablero);

        // Creamos los botones
        JButton botonTablas = new JButton("Tablas");
        JButton botonRendirse = new JButton("Rendirse");

        // Establecemos el tamaño de los botones
        Dimension buttonSize = new Dimension(150, 50);
        botonTablas.setPreferredSize(buttonSize);
        botonRendirse.setPreferredSize(buttonSize);

        // Añadimos ActionListener para el botón Ofrecer Tablas
        botonTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int confirmacion = JOptionPane.showConfirmDialog(frame, "¿Estás seguro que quieres ofrecer tablas?", "Confirmar Tablas", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    // Aquí puedes añadir la lógica para ofrecer tablas
                    JOptionPane.showMessageDialog(frame, "Has ofrecido tablas.");
                }
            }
        });

        // Añadimos ActionListener para el botón Rendirse
        botonRendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int confirmacion = JOptionPane.showConfirmDialog(frame, "¿Estás seguro que quieres rendirte?", "Confirmar Rendición", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    // Aquí puedes añadir la lógica para rendirse
                    JOptionPane.showMessageDialog(frame, "Te has rendido.");
                    
                    frame.dispose();
                }
            }
        });

        // Añadimos los botones al frame con GridBagConstraints para separarlos
        GridBagConstraints gbcBotones = new GridBagConstraints();
        gbcBotones.gridy = 1;
        gbcBotones.insets = new Insets(10, 10, 10, 10); // Márgenes para separar los botones

        gbcBotones.gridx = 0;
        gbcBotones.weightx = 0.0;
        gbcBotones.fill = GridBagConstraints.NONE;

        gbcBotones.gridx = 1;
        gbcBotones.insets = new Insets(10, 10, 10, 0); // Márgenes para el botón Tablas
        frame.add(botonTablas, gbcBotones);

        gbcBotones.gridx = 2;
        gbcBotones.insets = new Insets(10, 350, 10, 0); // Márgenes para el botón Rendirse
        frame.add(botonRendirse, gbcBotones);

        // Lo ponemos visible
        frame.setVisible(true);


        
    }//GEN-LAST:event_btnIJugadorActionPerformed

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTiendaActionPerformed

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjustesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnIA;
    private javax.swing.JButton btnIJugador;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTienda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPunt;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
